#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES=''
DESCRIPTION='Performs core system configuration. Most users would want this.'
CHROOTBIN='brightness croutonversion host-dbus'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
echo 'Preparing environment...' 1>&2
if [ ! "$VERSION" = '#VERSION' ]; then
    sed -i "s ^VERSION=.*\$ VERSION='$VERSION' " '/usr/local/bin/croutonversion'
fi

# Create the new environment file
oldenv='/etc/environment'
newenv='/etc/environment.new'
{
    echo '### begin crouton-generated environment variables'
    if [ "$PROXY" = 'unspecified' -o "$PROXY" = '#PROXY' ]; then
        grep -i '^[a-z]*_proxy' "$oldenv" 2>/dev/null || true
    elif [ -n "$PROXY" ]; then
        for var in http_proxy HTTP_PROXY https_proxy HTTPS_PROXY \
                   ftp_proxy FTP_PROXY; do
            echo "$var='$PROXY'"
        done
        for var in no_proxy NO_PROXY; do
            echo "$var='localhost,127.0.0.1'"
        done
    fi
    echo '### end crouton-generated environment variables'
    # Copy in previous user-environment settings
    if [ -r "$oldenv" ]; then
        awk '/^### begin/{x=1}!x;/^### end/{x=0}' "$oldenv"
    fi
} > "$newenv"
mv -f "$newenv" "$oldenv"

if [ ! "$MIRROR" = 'unspecified' ]; then
	if [ ! -e /etc/pacman.d/mirrorlist.croutonorig ]; then
		cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.croutonorig
	fi 
	cat > /etc/pacman.d/mirrorlist <<EOF
Server = $MIRROR/armv7h/\$repo
EOF
fi

#Remove some useless packages (there are more!)
pacman -R linux-firmware --noconfirm || true
pacman -R syslog-ng --noconfirm || true
pacman -R wpa_supplicant --noconfirm || true
pacman -R netcfg --noconfirm || true

echo 'Ensuring system is up-to-date...' 1>&2
pacman -Syu

# On release upgrade, keyboard-configuration might be reconfigured.
fixkeyboardmode

# Generate and set default locale
if [ ! -f '/etc/locale.conf' ]; then
    locale-gen --lang en_US.UTF-8
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
fi


