#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES=''
DESCRIPTION='Performs core system configuration. Most users would want this.'
CHROOTBIN='brightness croutonversion host-dbus'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
echo 'Preparing environment...' 1>&2
if [ ! "$VERSION" = '#VERSION' ]; then
    sed -i "s ^VERSION=.*\$ VERSION='$VERSION' " '/usr/local/bin/croutonversion'
fi

# Create the new environment file
oldenv='/etc/environment'
newenv='/etc/environment.new'
{
    echo '### begin crouton-generated environment variables'
    if [ "$PROXY" = 'unspecified' -o "$PROXY" = '#PROXY' ]; then
        grep -i '^[a-z]*_proxy' "$oldenv" 2>/dev/null || true
    elif [ -n "$PROXY" ]; then
        for var in http_proxy HTTP_PROXY https_proxy HTTPS_PROXY \
                   ftp_proxy FTP_PROXY; do
            echo "$var='$PROXY'"
        done
        for var in no_proxy NO_PROXY; do
            echo "$var='localhost,127.0.0.1'"
        done
    fi
    echo '### end crouton-generated environment variables'
    # Copy in previous user-environment settings
    if [ -r "$oldenv" ]; then
        awk '/^### begin/{x=1}!x;/^### end/{x=0}' "$oldenv"
    fi
} > "$newenv"
mv -f "$newenv" "$oldenv"

if [ -n "$MIRROR" ]; then
    if [ ! -e /etc/pacman.d/mirrorlist.croutonorig ]; then
	    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.croutonorig
    fi

    cat > /etc/pacman.d/mirrorlist <<EOF
Server = $MIRROR
EOF
fi

#Remove some useless packages (there are more!)
pacman -R linux-firmware --noconfirm || true
pacman -R syslog-ng --noconfirm || true
pacman -R wpa_supplicant --noconfirm || true
pacman -R netcfg --noconfirm || true

#Initialize pacman keyring (useless for arm)
if ! uname -m | grep '^arm' && [ `pacman-key -l 2>/dev/null | grep '^pub' | wc -l` -lt 2 ]; then
    echo 'Initializing pacman keyring...' 1>&2
    echo 'Note: If this gets stuck, generate entropy by moving the mouse around (e.g. random browsing).' 1>&2
    pacman-key --init
    pacman-key --populate archlinux
fi

echo 'Ensuring system is up-to-date...' 1>&2
pacman -Syu

# On release upgrade, keyboard-configuration might be reconfigured.
fixkeyboardmode

# Generate and set default locale
if [ ! -f '/etc/locale.conf' ]; then
    cp /etc/locale.gen /etc/locale.gen.croutonorig
    sed -i -e "s/^#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
fi

echo 'Syncing timezone...' 1>&2
# Link the timezone to Chromium OS
# Remove /etc/timezone: this tells Ubuntu/Debian that we are managing the
# content of /etc/localtime manually, and that it should not erase the symbolic
# link upon update, unless "dpkg-reconfigure tzdata" is called explicitly.
rm -f /etc/timezone

# /var/host/timezone/localtime is itself a symbolic link, but as long as the
# zoneinfo packages in the chroot and Chromium OS are the same, it'll be fine
ln -sfT /var/host/timezone/localtime /etc/localtime
