#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a target, but it's not selectable by the user. These are the commands
# that get executed at the very end of the generated prepare.sh.
# These commands are not optional and are automatically added to targets.

REQUIRES=''
DESCRIPTION=''
HOSTBIN='enter-chroot delete-chroot edit-chroot mount-chroot unmount-chroot'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

pacman --noconfirm --needed -S sudo
echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/00-wheel

# Add the primary user
if ! grep -q ":1000:" /etc/passwd; then
    username=
    while ! echo "$username" | grep -q '^[a-z][-a-z0-9_]*$'; do
        if [ -n "$username" ]; then
            echo 'Username must be lowercase letters, numbers, or dashes.' 1>&2
        fi
        echo -n 'Please specify a username for the primary user: ' 1>&2
        read username junk
    done
    useradd -G wheel,audio,video,users -m -u 1000 $username
    TRY=0
    while ! passwd $username && [ $TRY -lt 3 ]; do
        echo "passwd failed, retrying..."
        let TRY=TRY+1
    done

    if [ $TRY -eq 3 ]; then
	echo "passwd failed 3 times. You can always set the password by typing 'passwd $username' in the chroot."
    fi
fi

rm -f "$0"

if [ -n "$TIPS" ]; then
    echo "
Here's some tips:
$TIPS" 1>&2
fi

