#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Nested X11 install. Replaces X11 if specified first.'
CHROOTBIN='croutonclip croutonpowerd croutonwheel croutonwm croutonxinitrc-wrapper xinit'
CHROOTETC='xbindkeysrc-xephyr'
# Prevent X11 from being added if it hasn't already.
echo 'x11' >> "${TARGETDEDUPFILE:-/dev/null}"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Needed for croutonwheel to work
aurcompile mawk

#FIXME: Missing dmz-cursor-theme
pacman -S xorg-server-xephyr ratpoison xorg-utils xorg-server-utils xautomation xdotool xorg-xinput xorg-xinit xbindkeys \
    xclip openbsd-netcat --needed --noconfirm

# Compile croutoncursor
compile cursor '-lX11 -lXfixes -lXrender' \
    libx11 libxfixes libxrender

# Add a host Xauthority sentinel file
hostxauth='/etc/X11/host-Xauthority'
touch "$hostxauth"
chmod 444 "$hostxauth"

# Modify xserverrc
echo '#!/bin/sh -e
if [ -r "'"$hostxauth"'" ]; then
	export DISPLAY=":0" XAUTHORITY="'"$hostxauth"'"
	exec /usr/bin/Xephyr -fullscreen -host-cursor -nolisten tcp "$@"
else
	exec /usr/bin/X -nolisten tcp "$@"
fi
' > /etc/X11/xinit/xserverrc

# Add /usr/local/bin to ENV_PATH in /etc/login.defs (necessary for host startxfce4 to work)
if ! grep -q -e '^ENV_PATH.*[=:]/usr/local/bin:' -e '^ENV_PATH.*[=:]/usr/local/bin[ \t]*$' /etc/login.defs; then
	if [ ! -e /etc/login.defs.croutonorig ]; then
		cp /etc/login.defs /etc/login.defs.croutonorig
	fi
	sed -i -e "s|^\(ENV_PATH.*PATH=\)\(.*\)$|\1/usr/local/bin:\2|" /etc/login.defs
fi

TIPS="$TIPS
You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
"

TIPS="$TIPS
You probably want to run the crouton-clip application on Chromium OS, so that
the clipboard can be synchronized between Chromium OS and the chroot desktops.
"

### append x11-common
