#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

PIPEIN='/tmp/croutonwebsocket-in'
PIPEOUT='/tmp/croutonwebsocket-out'
PIPELOCK='/tmp/croutonwebsocket-lock'

# Write a command to croutonwebsocket, and read back response
websocketcommand() {
        (
            # Make sure we do not create $PIPEIN if it does not exist
            [ -p "$PIPEIN" -a -p "$PIPEOUT" ] || {
                echo "EError $PIPEIN or $PIPEOUT are not pipes." > "$cliptmp2"
                exit 0
            }
            flock 5
            cat > "$PIPEIN"
            cat "$PIPEOUT"
        ) 5>"$PIPELOCK"
}

USAGE="${0##*/} [-n] URL
Open an URL in Chromium OS (requires crouton extension).
If -s is specified, switch to Chromium OS."

if [ -z "$*" ]; then
    echo "$USAGE" 1>&2; exit 2;
fi

switch=''
if [ "$1" = "-s" ]; then
    switch='y'
    shift
fi

STATUS="`echo -n U"$*" | websocketcommand`"

if [ ! "$STATUS" = "UOK" ]; then
    echo "$STATUS" | tail -c +2
    exit 1
fi

if [ -n "$switch" ]; then
    croutoncycle chromium
fi
