#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Adds a :# to the xinit command line, where # is the first available display
# number. Also adds the -- to the command line and references the global
# xserverrc if it isn't already there.  By putting this in /usr/local/bin, PATH
# will prefer it and scripts that call xinit will automagically work.

croutonwm='/usr/local/bin/croutonwm'
if [ -x "$croutonwm" ]; then
    . "$croutonwm"
fi

xserverrc='/etc/X11/xinit/xserverrc'
dash='--'
for arg in "$@"; do
    if [ -z "$dash" ]; then
        # Check if there's a xserverrc specified.
        if [ ! "${arg#/}" = "$arg" ]; then
            xserverrc=''
        fi
        break
    elif [ "$arg" = '--' ]; then
        dash=
    fi
done

xinitrc=''
# If we only have xinitrc as client parameter, prepare a custom xinitrc
if [ -f "$1" ] && [ "$dash" = '--' -o "$2" = '--' ]; then
	xinitrc=`mktemp --tmpdir=/tmp 'crouton-xinitrc.XXX'`
	cat > $xinitrc <<EOF
#!/bin/sh

sh $1
# Wait for all processes in the background to complete
wait
# Switch window to ensure keyboard is copied
if [ -n "$hostxauth" ]; then
    DISPLAY=:0 XAUTHORITY=$hostxauth ratpoison -c prev
else
    # FIXME: Code for non-Xephyr
    true
fi
# Make sure we have enough time to copy the data
sleep 2
rm $xinitrc
EOF
	shift 1
fi

disp=0
while [ -f "/tmp/.X$disp-lock" ]; do
    disp=$((disp+1))
done

# Function to exec the parameters when the display has been created.
queuelaunch() {
    (while sleep 1; do
        if [ -S "/tmp/.X11-unix/X$disp" ]; then
            DISPLAY=":$disp" exec "$@" >/dev/null 2>&1
        fi
    done) &
}

# Launch the powerd poker daemon
queuelaunch croutonpowerd --daemon

# Launch the cursor relayer and keyboard shortcuts if in xephyr
if [ -n "$hostxauth" ]; then
    queuelaunch env DISPLAY=':0' XAUTHORITY="$hostxauth" croutoncursor ":$disp"

    ln -sf '/etc/crouton/xbindkeysrc-xephyr' "$HOME/.xbindkeysrc"
    queuelaunch xbindkeys
fi

# Launch touchegg if it is requested.
toucheggconf='/etc/touchegg.conf'
if [ -f "$toucheggconf" ]; then
    mkdir -p "$HOME/.config/touchegg"
    ln -sf "$toucheggconf" "$HOME/.config/touchegg/"
    queuelaunch touchegg
fi

exec /usr/bin/xinit $xinitrc "$@" $dash $xserverrc ":$disp"
