#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This isn't a real target; it's the common commands for installing various
# forms of X11.

### Append to prepare.sh:
if [ "${DISTROAKA:-"$DISTRO"}" = 'arch' ]; then
    # Add /usr/local/bin to ENV_PATH in /etc/login.defs (necessary for host
    # startxfce4 to work)
    # The root cause is actually a bug in su/bash, where /etc/profile is not
    # sourced from su, even when the '-' parameter is passed.
    # See: https://bugs.archlinux.org/task/31831
    # This probably affects other distributions as well, but in Ubuntu
    # /etc/login.defs contains /usr/local/bin and startxfce4 then works fine. 
    if ! grep -q -e '^ENV_PATH[ \t]*PATH=/usr/local/bin:' /etc/login.defs; then
        if [ ! -e /etc/login.defs.croutonorig ]; then
	        cp /etc/login.defs /etc/login.defs.croutonorig
        fi
        sed -i -e "s|^\(ENV_PATH[ \t]*PATH=\)\(.*\)$|\1/usr/local/bin:\2|" /etc/login.defs
    fi
fi     

# Generate the executable that outputs the equivalent of base::TimeTicks::Now()
compile ticks -lrt

# Install utilities and links for powerd-poking daemon
# FIXME: arch: libxss misses dependency on xprintidle
install --minimal arch=libxss, arch=aur:xprintidle,xprintidle dbus
ln -sf croutonpowerd /usr/local/bin/gnome-screensaver-command
ln -sf croutonpowerd /usr/local/bin/xscreensaver-command

# Add a blank Xauthority to all users' home directories
touch /etc/skel/.Xauthority
chmod 600 /etc/skel/.Xauthority

# Create /usr/share/desktop-directories to avoid issues with xdg-desktop-menu
mkdir -p /usr/share/desktop-directories

# Update policies for mounting and unmounting devices with udisks2
mkdir -p '/etc/polkit-1/localauthority/10-vendor.d'
cat > '/etc/polkit-1/localauthority/10-vendor.d/10-crouton-udisks2.pkla' <<EOF
[Allow mounting when started from crosh]
Identity=*
Action=org.freedesktop.udisks*.filesystem-mount
ResultAny=auth_admin
ResultInactive=yes
ResultActive=yes

[Allow eject when started from crosh]
Identity=*
Action=org.freedesktop.udisks*.*eject*
ResultAny=auth_admin
ResultInactive=yes
ResultActive=yes

[Disallow unmounting of Chromium OS mounts; it won't work]
Identity=*
Action=org.freedesktop.udisks*.filesystem-unmount-others
ResultAny=no
ResultInactive=no
ResultActive=no
EOF
