#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Nested X11 install. Replaces X11 if specified first.'
CHROOTBIN='croutoncycle croutonpowerd croutonwheel croutonwm croutonxinitrc-wrapper xinit'
CHROOTETC='xbindkeysrc.scm xserverrc-xephyr'
# Prevent X11 from being added if it hasn't already.
echo 'x11' >> "${TARGETDEDUPFILE:-/dev/null}"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
XMETHOD=xephyr

if [ "$RELEASE" = 'quantal' ]; then
    # As of 2013-01-08, Quantal's Xephyr lacks GLX. Download one manually.
    install wget
    url="$MIRROR/pool/universe/x/xorg-server/"
    xvers="`wget -O- "$url" \
        | sed -n 's/.*\(xserver-xephyr_1\.11\.4-0ubuntu[0-9][0-9]\.[0-9]*_'"$ARCH"'\.deb\).*/\1/p' \
        | sort -V | tail -n1`"
    if [ -z "$xvers" ]; then
        error 1 'Error retreiving latest Xephyr version.'
    fi
    url="$url/$xvers"
    deb='/tmp/xephyr.deb'
    rm -f "$deb"
    wget --no-check-certificate "$url" -O "$deb"
    # Install the package and delete it.
    install_pkg "$deb"
    rm -f "$deb"
    # Add the apt preference to avoid immediate upgrade
    cat > /etc/apt/preferences.d/xserver-xephyr <<EOF
Package: xserver-xephyr
Pin: version <1.13.3-0ubuntu4
Pin-Priority: -1
EOF
fi

# xserver-xephyr won't auto replace the manually-downloaded version.
# FIXME: What is the purpose of dmz-cursor-theme and libgl1-mesa-dri?
install --minimal \
    arch=xorg-server-xephyr,xserver-xephyr arch=,xinit ratpoison \
    arch=,dmz-cursor-theme \
    arch=ttf-dejavu, \
    arch=,libgl1-mesa-dri \
    arch=xorg-utils,x11-utils arch=xorg-server-utils,x11-xserver-utils \
    xautomation xdotool arch=xorg-xinput,xinput xterm \
    arch=aur:mawk,mawk

# Compile croutoncursor
compile cursor '-lX11 -lXfixes -lXrender' \
    arch=,libx11-dev arch=,libxfixes-dev arch=,libxrender-dev

TIPS="$TIPS
You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
"

### append x11-common
